name: Build
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Full Theos Env Fast
        run: |
          sudo apt update -y
          sudo apt install git build-essential perl -y
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo THEOS=$HOME/theos >> $GITHUB_ENV
          mkdir -p $HOME/theos/sdks

      - name: Compile
        run: make clean && make package

      - name: Get Deb
        uses: actions/upload-artifact@v4
        with:
          path: packages/*.deb
